# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_auto_20170831_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='branch',
            field=models.CharField(choices=[('AR', 'Architecture'), ('CE', 'Civil Engg.'), ('CH', 'Chemical Engg.'), ('CS', 'Computer Science'), ('EC', 'Electronics & Comm.'), ('EE', 'Electrical & Elec.'), ('ME', 'Mechanical Engg.'), ('PE', 'Production Engg.'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
