# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0012_auto_20170831_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_no',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
    ]
